### ISSUE TITLE
Cannot read big wig file saved using BigWig.write(..)

### ISSUE THREAD

**Issue by iromeo** [superbobry/big#12]
```
Caused by: java.lang.IllegalStateException: bad signature
    at kotlin.KotlinPackage$Preconditions$cd8e6ab4.check(Preconditions.kt:66)
    at kotlin.KotlinPackage.check(Unknown Source)
    at org.jetbrains.bio.big.SeekableDataInput.guess(SeekableDataIO.kt:96)
    at org.jetbrains.bio.big.BigFile$Header$Companion.read(BigFile.kt:130)
    at org.jetbrains.bio.big.BigFile.<init>(BigFile.kt:19)
    at org.jetbrains.bio.big.BigWigFile.<init>(BigWig.kt:15)
    at org.jetbrains.bio.big.BigWigFile$Companion.read(BigWig.kt:62)
    at org.jetbrains.bio.browser.tracks.MethylomeRawDataTrackView.readFromWig(MethylomeRawDataTrackView.kt:142)
    at org.jetbrains.bio.browser.tracks.MethylomeRawDataTrackView.getData(MethylomeRawDataTrackView.kt:127)
    ...
```

My big wig file: https://www.dropbox.com/s/jeszfc9zh5apuoh/fix_me_hg19_0_%2B.bw?dl=0
My chromInfo.txt; https://www.dropbox.com/s/93lv713wcmhkfei/chromInfo.txt?dl=0

**Comment by iromeo** [comment]
Same issue. I've successfully  load files created by you (experiments/browser/mc_view/fix_me__), but have similar signature problem with files saved by my machine (fix_me1__).

```
Caused by: java.lang.IllegalStateException: bad signature
    at kotlin.KotlinPackage$Preconditions$cd8e6ab4.check(Preconditions.kt:66)
    at kotlin.KotlinPackage.check(Unknown Source)
    at org.jetbrains.bio.big.SeekableDataInput.guess(SeekableDataIO.kt:96)
    at org.jetbrains.bio.big.BigFile$Header$Companion.read(BigFile.kt:227)
    at org.jetbrains.bio.big.BigFile.<init>(BigFile.kt:23)
    at org.jetbrains.bio.big.BigWigFile.<init>(BigWig.kt:14)
    at org.jetbrains.bio.big.BigWigFile$Companion.read(BigWig.kt:65)
    at org.jetbrains.bio.browser.tracks.MethylomeRawDataTrackView.readFromWig(MethylomeRawDataTrackView.kt:158)
    at org.jetbrains.bio.browser.tracks.MethylomeRawDataTrackView.getData(MethylomeRawDataTrackView.kt:143)
    at org.jetbrains.bio.browser.tracks.MethylomeRawDataTrackView.getData(MethylomeRawDataTrackView.kt:27)
    at org.jetbrains.bio.browser.tracks.BinnedDataTrackView.computeScale(BinnedDataTrackView.kt:140)
    at org.jetbrains.bio.browser.util.TrackViewRenderer.lambda$computeScale$30(TrackViewRenderer.java:165)
    at org.jetbrains.bio.browser.util.TrackViewRenderer$$Lambda$63/1817053179.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Collections$2.tryAdvance(Collections.java:4717)
    at java.util.Collections$2.forEachRemaining(Collections.java:4725)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
    at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
    at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.jetbrains.bio.browser.util.TrackViewRenderer.computeScale(TrackViewRenderer.java:167)
    at org.jetbrains.bio.browser.util.TrackViewRenderer.paintToImage(TrackViewRenderer.java:135)
    at org.jetbrains.bio.browser.desktop.DrawingArea.paintToBuffer(DrawingArea.java:167)
    at org.jetbrains.bio.browser.desktop.DrawingArea$$Lambda$60/34941421.call(Unknown Source)
    at org.jetbrains.bio.util.concurrent.CancellableTask.lambda$execute$4(CancellableTask.java:67)
    at org.jetbrains.bio.util.concurrent.CancellableTask$$Lambda$61/456356811.call(Unknown Source)
    at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[21:59:43] ERROR 49633
Caused by: java.lang.ArrayIndexOutOfBoundsException: 49633
    at org.jetbrains.bio.browser.tracks.TracksPackage$BinnedDataTrackView$2021808e.min(BinnedDataTrackView.kt:581)
    at org.jetbrains.bio.browser.tracks.BinnedDataTrackView$computeScale$arrayMin$1.invoke(BinnedDataTrackView.kt:152)
...
```

**Comment by iromeo** [comment]
```
$ hexdump -n 10 fix_me_hg19_0_-.bw
0000000 26 fc 8f 88 04 00 00 00 40 00
000000a
$ hexdump -n 10 fix_me1_hg19_0_-.bw
0000000 26 fc 8f 88 04 00 00 00 40 00
000000a
$ diff fix_me1_hg19_0_+.bw fix_me_hg19_0_+.bw
Binary files fix_me1_hg19_0_+.bw and fix_me_hg19_0_+.bw differ
```
