### ISSUE TITLE
Kotlin access error

### ISSUE THREAD

**Issue by olegs** [superbobry/big#24]
```
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access method kotlin.LazyKt.getValue(Lkotlin/Lazy;Ljava/lang/Object;Lkotlin/reflect/KProperty;)Ljava/lang/Object; from class org.jetbrains.bio.big.BigFile
    at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1000)
    at org.jetbrains.bio.browser.tasks.CancellableTask.get(CancellableTask.kt:61)
    ... 19 more
Caused by: java.lang.IllegalAccessError: tried to access method kotlin.LazyKt.getValue(Lkotlin/Lazy;Ljava/lang/Object;Lkotlin/reflect/KProperty;)Ljava/lang/Object; from class org.jetbrains.bio.big.BigFile
    at org.jetbrains.bio.big.BigFile.getChromosomes(BigFile.kt)
    at org.jetbrains.bio.big.BigWigFile.queryInternal$big_compileKotlin(BigWig.kt:59)
    at org.jetbrains.bio.big.BigFile$query$1.invoke(BigFile.kt:193)
    at org.jetbrains.bio.big.BigFile$query$1.invoke(BigFile.kt:19)
    at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:238)
    at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:226)
    at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:234)
    at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:226)
    at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:503)
    at kotlin.sequences.SequencesKt.toCollection(Unknown Source)
    at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:552)
    at kotlin.sequences.SequencesKt.toMutableList(Unknown Source)
    at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:520)
    at kotlin.sequences.SequencesKt.toList(Unknown Source)
    at org.jetbrains.bio.big.BigWigFile.summarizeInternal$big_compileKotlin(BigWig.kt:18)
    at org.jetbrains.bio.big.BigFile.summarize(BigFile.kt:101)
    at org.jetbrains.bio.big.BigFile.summarize$default(BigFile.kt:84)
    at org.jetbrains.bio.browser.tracks.BigWigTrackView.summarize(BigWigTrackView.kt:364)
    at org.jetbrains.bio.browser.tracks.BigWigTrackView.byPixelData(BigWigTrackView.kt:153)
    at org.jetbrains.bio.browser.tracks.BigWigTrackView.access$byPixelData(BigWigTrackView.kt:31)
    at org.jetbrains.bio.browser.tracks.BigWigTrackView$initConfig$dataOn$1.invoke(BigWigTrackView.kt:129)
    at org.jetbrains.bio.browser.tracks.BigWigTrackView$initConfig$dataOn$1.invoke(BigWigTrackView.kt:31)
    at org.jetbrains.bio.browser.tracks.BigWigTrackView.initConfig(BigWigTrackView.kt:133)
    at org.jetbrains.bio.browser.util.TrackViewRenderer.paintToImage(TrackViewRenderer.kt:80)
    at org.jetbrains.bio.browser.util.TrackViewRenderer.paintHeadless(TrackViewRenderer.kt:44)
    at org.jetbrains.bio.browser.headless.HeadlessGenomeBrowser.lambda$null$0(HeadlessGenomeBrowser.java:130)
    at org.jetbrains.bio.browser.headless.HeadlessGenomeBrowser$$Lambda$34/610737021.invoke(Unknown Source)
    at org.jetbrains.bio.ext.LoggerExtensionsKt.time(LoggerExtensions.kt:18)
    at org.jetbrains.bio.browser.headless.HeadlessGenomeBrowser.lambda$paint$1(HeadlessGenomeBrowser.java:128)
    at org.jetbrains.bio.browser.headless.HeadlessGenomeBrowser$$Lambda$32/2037998802.call(Unknown Source)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by superbobry** [comment]
This is due to the a Kotlin compiler version conflict. Will fix in the next release.
