### ISSUE TITLE
java.lang.IllegalArgumentException in BedEntry.<init>

### ISSUE THREAD

**Issue by iromeo** [superbobry/big#29]
I've tried to open "*.bigBed" file from https://www.encodeproject.org/annotations/ENCSR323UGM/

```
Exception in thread "main" java.lang.IllegalArgumentException: Failed requirement
	at org.jetbrains.bio.big.BedEntry.<init>(Bed.kt:75)
	at org.jetbrains.bio.big.BedEntry$Companion.invoke(Bed.kt:53)
	at org.jetbrains.bio.big.BigBedFile$queryInternal$1.invoke(BigBed.kt:78)
	at org.jetbrains.bio.big.BigBedFile$queryInternal$1.invoke(BigBed.kt:14)
	at org.jetbrains.bio.RomBuffer.with$big_compileKotlin(SeekableDataIO.kt:148)
	at org.jetbrains.bio.big.BigBedFile.queryInternal$big_compileKotlin(BigBed.kt:69)
	at org.jetbrains.bio.big.BigFile$query$1.invoke(BigFile.kt:205)
	at org.jetbrains.bio.big.BigFile$query$1.invoke(BigFile.kt:27)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:241)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:229)
	at org.jetbrains.bio.experiments.methylome.tools.FooKt.bigBedToBed(Foo.kt:14)
	at org.jetbrains.bio.experiments.methylome.tools.FooKt.main(Foo.kt:23)
```

```
# example.kt
fun bigBedToBed(inputPath: Path) {
       BigBedFile.read(inputPath).use { bbf ->
           for (chromosome in bbf.chromosomes.valueCollection()) {
               for ((chrom, start, end) in bbf.query(chromosome)) {
                   // See 'BedEntry' for a complete list of available
                   // attributes.
                   println("$chrom\t$start\t$end")
               }
           }
       }
   }
fun main(args: Array<String>) {
    bigBedToBed("ENCFF086AYQ.bigBed".toPath())

}
```

Issue is due to BedEntry expects "rest" to be split by comma delimiter, but actually it is `\t`, i.e **rest**=`15_Quies	0	.	0	9800	255,255,255`

```
#Bed.kt
companion object {
        operator fun invoke(chrom: String, start: Int, end: Int, rest: String = ""): BedEntry {
            val it = rest.split(',', limit = 4).iterator()
            return BedEntry(
                chrom, start, end,
                name = if (it.hasNext()) it.next() else "",
                score = if (it.hasNext()) it.next().toShort() else 0,
                strand = if (it.hasNext()) it.next().first() else '.',
                rest = if (it.hasNext()) it.next() else ""
            )
        }
    }
```

**Comment by superbobry** [comment]
I think `big` is wrong here. Feel free to alter the character in the `split` call.

**Comment by iromeo** [comment]
UCSC bigBedToBed generates incorrect *.bed file if we use `,` as separator instead of `\t`. So I think `\t` is right choice.
