### ISSUE TITLE
Encode *.bigBed files: NumberFormatException: For input string: "5.30862042004096"

### ISSUE THREAD

**Issue by iromeo** [superbobry/big#33]
Error reading ENCODE big bed files. E.g. https://www.encodeproject.org/experiments/ENCSR000ATN `ENCFF213XMK.bigBed`
```
[2017-11-20 15:40:40] GenomeBrowser [ERROR] Failed to preprocess track ENCFF213XMK_peaks_r2.bigBed
Caused by: java.lang.NumberFormatException: For input string: "5.30862042004096"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.jetbrains.bio.big.BedEntry$Companion.invoke(Bed.kt:70)
	at org.jetbrains.bio.big.BigBedFile.queryInternal$big(BigBed.kt:83)
	at org.jetbrains.bio.big.BigFile$query$1.invoke(BigFile.kt:224)
	at org.jetbrains.bio.big.BigFile$query$1.invoke(BigFile.kt:33)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:252)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:240)
	at org.jetbrains.bio.browser.tracks.impl.BigBedTrackView$Companion.calc80percentileAndLegend(BigBedTrackView.kt:281)
	at org.jetbrains.bio.browser.tracks.impl.BigBedTrackView$Companion.access$calc80percentileAndLegend(BigBedTrackView.kt:209)
	at org.jetbrains.bio.browser.tracks.impl.BigBedTrackView$Companion$fromBigBed$1.preprocess(BigBedTrackView.kt:234)
	at org.jetbrains.bio.browser.GenomeBrowser.preprocess(GenomeBrowser.kt:277)
	at org.jetbrains.bio.browser.desktop.DesktopGenomeBrowser$addAndProcessNewTracks$1.run(DesktopGenomeBrowser.kt:154)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by iromeo** [comment]
`ENCFF213XMK.bigBed` bed content (https://www.encodeproject.org/files/ENCFF213XMK/@@download/ENCFF213XMK.bigBed):
```
chr1	714023	714503	.	832	.	34.56398	-1.00000	4.91755	240
chr1	805139	805538	.	1000	.	193.07668	-1.00000	4.91755	171
chr1	838931	839411	.	539	.	13.42580	-1.00000	3.99974	240
chr1	840007	840369	.	1000	.	172.56030	-1.00000	4.91755	156
chr1	856342	856822	.	715	.	48.44700	-1.00000	4.91755	240
```
We can convert it to '*.bb' using `bedToBigBed in.bed /mnt/stripe/bio/genomes/hg19/hg19.chrom.sizes out.bb -type=bed6+3`

So we probably need to support similar formats, like UCSC `bedToBigBed` utility:
```
bedToBigBed v. 2.7 - Convert bed file to bigBed. (BigBed version: 4)
usage:
   bedToBigBed in.bed chrom.sizes out.bb

...

options:
   -type=bedN[+[P]] :
                      N is between 3 and 15,
                      optional (+) if extra "bedPlus" fields,
                      optional P specifies the number of extra fields. Not required, but preferred.
                      Examples: -type=bed6 or -type=bed6+ or -type=bed6+3
                      (see http://genome.ucsc.edu/FAQ/FAQformat.html#format1)
```

**Comment by iromeo** [comment]
BigBed format defines only first 3 bed fields, all other fields are stored in TAB separated string. We have to parse this string while querying entries or calculating summary levels while saving.  So probably we can return by default BedEntries with 3 fields + `rest` string. And instead of limiting just let user to parse/handler `rest` field as he wants. Seems users can freely interpret bed format and generate malformed *.bigBed files, so we can easily support all cases using such workaround. So BedEntry will be reverted to ~ big 0.4.x format.

Also we can add default BedEntry.parse(fieldsNumber, extraFieldsNumber) method which converts simple entry to detailed one with all other BED fields (e.g. rgb color, thickStart, thickEnd, ..) and additional 'extra fields'. Such method is expected to cover most usecases without additional support from user.

At the moment current API doesn't allow us easily add "fieldsNumber, extraFieldsNumber" args to BigBedFile.read() and BigBedFile.write() methods for dedicated args parsing. The issue is in coverage summarising while saving files. Current API is to generic, so summarising code is shared both for BigBed and BigWig files, we cannot easily push "fieldsNumber, extraFieldsNumber" fields there.

**Comment by iromeo** [comment]
Done
