### ISSUE TITLE
java.lang.IllegalArgumentException: n must be >0

### ISSUE THREAD

**Issue by iromeo** [superbobry/big#34]
Occurred during *.bb writing
```
Caused by: java.lang.IllegalArgumentException: n must be >0
	at org.jetbrains.bio.big.ChromosomeInterval.slice$big(Interval.kt:105)
	at org.jetbrains.bio.big.BigBedFile.summarizeInternal$big(BigBed.kt:32)
	at org.jetbrains.bio.big.BigFile$Post.zoomAt(BigFile.kt:454)
	at org.jetbrains.bio.big.BigFile$Post.zoom$big(BigFile.kt:419)
	at org.jetbrains.bio.big.BigFile$Post.zoom$big$default(BigFile.kt:413)
	at org.jetbrains.bio.big.BigBedFile$Companion.write(BigBed.kt:291)
	at org.jetbrains.bio.big.BigBedFile$Companion.write$default(BigBed.kt:170)
```

**Comment by iromeo** [comment]
Fixed in 0.5.2
